# -*- coding: utf-8 -*-
"""Weather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18gJmUeCYSmi097WAqSi80NlWjduxDEJz
"""
import requests
import json

import requests

weatherapi_key = "99aef283258d437fac031135250807"  # replace with your real key

def get_weather(city):
    url = f"http://api.weatherapi.com/v1/current.json?key={weatherapi_key}&q={city}"
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        condition = data['current']['condition']['text']
        temp = data['current']['temp_c']
        humidity = data['current']['humidity']
        wind = data['current']['wind_kph']
        report = (
            f"Weather in {city}:\n"
            f"Condition: {condition}\n"
            f"Temperature: {temp}°C\n"
            f"Humidity: {humidity}%\n"
            f"Wind Speed: {wind} kph"
        )
        return report
    else:
        return f"❌ Weather information not available for {city}."

def get_weather_telugu(city):
    url = f"http://api.weatherapi.com/v1/current.json?key={weatherapi_key}&q={city}"
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        condition = data['current']['condition']['text']
        temp = data['current']['temp_c']
        humidity = data['current']['humidity']
        wind = data['current']['wind_kph']
        report = (
           f"{city} లో వాతావరణ నివేదిక:\n"
            f"పరిస్థితి: {condition}\n"
            f"ఉష్ణోగ్రత: {temp} డిగ్రీల సెల్సియస్\n"
            f"తేమ శాతం: {humidity}%\n"
            f"గాలివేగం: {wind} కి.మీ/గంటకి"
        )
        return report
    else:
       return f"❌ {city} యొక్క వాతావరణాన్ని పొందలేకపోయాము."


def get_weather_hindi(city):
    url = f"http://api.weatherapi.com/v1/current.json?key={weatherapi_key}&q={city}"
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        condition = data['current']['condition']['text']
        temp = data['current']['temp_c']
        humidity = data['current']['humidity']
        wind = data['current']['wind_kph']
        report = (
            f"{city} में मौसम की जानकारी:\n"
            f"स्थिति: {condition}\n"
            f"तापमान: {temp} डिग्री सेल्सियस\n"
            f"नमी: {humidity}%\n"
            f"हवा की गति: {wind} किलोमीटर प्रति घंटा"
)

        return report
    else:
       return f"❌ {city} के मौसम की जानकारी प्राप्त नहीं हो सकी।"

print(get_weather("Guntur"))

print(get_weather_telugu("Guntur"))

print(get_weather_hindi("Guntur"))

from gtts import gTTS  # (✅ all lowercase: gtts)

from IPython.display import Audio

def speak_weather(report, lang='te'):
    tts = gTTS(text=report, lang=lang)
    tts.save("weather.mp3")
    return Audio("weather.mp3")
def speak_weather(report, lang='hi'):
    tts = gTTS(text=report, lang=lang)
    tts.save("weather.mp3")
    return Audio("weather.mp3")
def speak_weather(report, lang='en'):
    tts = gTTS(text=report, lang=lang)
    tts.save("weather.mp3")
    return Audio("weather.mp3")

report = get_weather_hindi("Guntur")
speak_weather(report, lang='hi')

report= get_weather_telugu("Guntur")
speak_weather(report, lang='te')

report = get_weather("Guntur")
speak_weather(report, lang='en')

def detect_language_hint(user_input):
    if "తెలుగులో" in user_input or "తెలుగు" in user_input:
        return "te"
    elif "हिंदी" in user_input or "हिन्दी" in user_input:
        return "hi"
    else:
        return "en"  # Default fallback

def weather_assistant(user_input, city):
    lang = detect_language_hint(user_input)

    if lang == "te":
        report = get_weather_telugu(city)
    elif lang == "hi":
        report = get_weather_hindi(city)
    else:
        report = get_weather(city)  # English

    return speak_weather(report, lang)

weather_assistant("తెలుగులో చెప్పు", "Guntur")
weather_assistant("हिंदी में बताओ", "Guntur")
weather_assistant("Tell me the weather", "Guntur")

weather_assistant("हिंदी में बताओ", "Guntur")

weather_assistant("Tell me the weather", "Guntur")

import joblib

